In [1]:
import numpy as np

from sklearn.datasets import load_diabetes

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_diabetes(return_X_y=True)

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [9]:
lr.coef_

array([ -30.28005126, -262.76289069,  493.07008697,  347.82194346,
       -672.14050145,  403.42301215,   12.28161296,  169.94922111,
        707.09649678,   56.79760838])

In [11]:
lr.intercept_

153.51996134471815

In [21]:
import random

class MiniBatchGradientDescentRegressor:
    
    def __init__(self,batch_size,learning_rate,epochs):
        
        self.coef_ = None
        self.intercept_ = None
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        self.intercept = 0
        self.coefficient = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                random_index = random.sample(range(X_train.shape[0]),self.batch_size)
                y_hat = np.dot(X_train[random_index],self.coefficient) + self.intercept
                deri_intercept = -2 * np.mean(y_train[random_index] - y_hat)
                self.intercept = self.intercept - (self.learning_rate * deri_intercept)

                deri_coefficient = -2 * np.dot((y_train[random_index] - y_hat),X_train[random_index])
                self.coef_ = self.coefficient - (self.learning_rate * deri_coefficient)
        
        print(self.intercept,self.coefficient)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coefficient) + self.intercept

In [23]:
mbr = MiniBatchGradientDescentRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [25]:
mbr.fit(X_train,y_train)

152.64842584624338 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [43]:
lr.intercept_

153.51996134471815

In [27]:
from sklearn.linear_model import SGDRegressor

In [29]:
sgd = SGDRegressor(learning_rate='constant', eta0=0.1)

In [31]:
batch_size = 35

for i in range(100):
    
    random_index = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[random_index],y_train[random_index])

In [33]:
sgd.coef_

array([   8.40704149,  -86.33182833,  356.88375253,  257.86400338,
         22.02390335,  -14.62604634, -186.19624739,  148.77991692,
        284.73694921,  132.22325653])

In [35]:
sgd.intercept_

array([164.00456489])